### ISSUE TITLE
ImportError: No module named tf.models.rnn

### ISSUE THREAD

**Issue by MansourTrabelsi** [Guanghan/ROLO#20]
running this first command " ./experiments/testing/ROLO_network_test_all.py "  gave me this error : 
Traceback (most recent call last):
  File "./../experiments/testing/ROLO_network_test_all.py", line 30, in <module>
    from tf.models.rnn import rnn, rnn_cell
ImportError: No module named tf.models.rnn

**Comment by Vivianyzw** [comment]
It is the problem of tensorflow version. You can change the "from tf.models.rnn import rnn, rnn_cell" into " from tensorflow.contrib import rnn, from tensorflow.python.ops.nn import rnn_cell". Coz the module rnn and cell_rnn are put into the different positions in version 1.0 or above.

**Comment by MansourTrabelsi** [comment]
Thank you a lot @Vivianyzw

**Comment by groot-1313** [comment]
Hi, 

@Vivianyzw I tried what you mentioned, but now I face the following error:

>outputs, state = rnn(cell, [_X[step]], state)
TypeError: 'module' object is not callable
