### ISSUE TITLE
Bad link in Readme

### ISSUE THREAD

**Issue by RayBB** [Guanghan/ROLO#24]
In the readme the results link doesn't point to anything

`Or download the results at [Results](http://).
`

**Comment by MansourTrabelsi** [comment]
I remark this too.
Have you faced this problem : Resource exhausted: OOM when allocating tensor with shape[8204,16408] ??
Thank oyu

**Comment by halaneji** [comment]
What version of tensorflow  this code is developed???

**Comment by AloshkaD** [comment]
@MansourTrabelsi 
سلام منصور
This error generally occurs when you train on a lower end GPU. I would go with TitanX, at least.

**Comment by MansourTrabelsi** [comment]
Salem.
I have Nvidia 730 M, 2Gb.

**Comment by AloshkaD** [comment]
That's too basic. I would open AWS account and test the network there.


________________________________
