### ISSUE TITLE
How can i use the codes in the video without ground truth?

### ISSUE THREAD

**Issue by Anida-qin** [Guanghan/ROLO#28]
@Guanghan 
Hi ! 
I m reading the codes now. But i find when i want to test the algorithm. Test images also need to have ground truth to get the best location. I m confused.. Do i misunderstand something?  So how can i use the codes in the video without ground truth,
Best wishes

**Comment by lihaixiang** [comment]
@Anida.qin
Hello
I am confused too.
According to the codes, when testing, the model need the information from yolo(such as feature map and detection box), however, there may be more than one detection boxes，if we do not know the  ground truth, then we cannot judgment which detection boxe should be sent into rolo(LSTM part)
i have many questiones about this paper

**Comment by Anida-qin** [comment]
@lihaixiang  
So this paper choose the biggest iou as boxes sent into rolo.. So i think it is more like another bounding regression rather than tracking
Anyways, i think the LSTM idea is a good idea to do with video. I m not going through this code anymore. If u have problem, feel free to open a new issue.
