### ISSUE TITLE
where is the module ROLO_utils?

### ISSUE THREAD

**Issue by adjfk** [Guanghan/ROLO#9]

**Comment by skywo1f** [comment]
Traceback (most recent call last):
  File "./experiments/testing/ROLO_network_test_all.py", line 27, in <module>
    import ROLO_utils as utils
ImportError: No module named ROLO_utils

**Comment by AydinAlptug** [comment]
Having the same issue. What may be the solution?

**Comment by abassino** [comment]
you can find it at "utils.ROLO_utils" (import utils.ROLO_utils as utils)
